# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2019, Qiskit Development Team
# This file is distributed under the same license as the Qiskit package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Qiskit \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-06-03 15:29-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../../../autodoc/qiskit.providers.ibmq.api.exceptions.rst:2
msgid "qiskit.providers.ibmq.api.exceptions module"
msgstr ""

#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions:1
msgid "Exceptions for IBMQ Connector."
msgstr ""

#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions.ApiError:1
msgid "ベースクラス: :class:`qiskit.providers.ibmq.exceptions.IBMQError`"
msgstr ""

#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions.ApiError:1
msgid "IBMQConnector API error handling base class."
msgstr ""

#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions.BadBackendError:1
#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions.CredentialsError:1
#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions.RegisterSizeError:1
#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions.WebsocketError:1
msgid "ベースクラス: :class:`qiskit.providers.ibmq.api.exceptions.ApiError`"
msgstr ""

#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions.BadBackendError:1
msgid "Unavailable backend error."
msgstr ""

#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions.CredentialsError:1
msgid "Exception associated with bad server credentials."
msgstr ""

#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions.RegisterSizeError:1
msgid "Exception due to exceeding the maximum number of allowed qubits."
msgstr ""

#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions.WebsocketError:1
msgid "Exceptions related to websockets."
msgstr ""

#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions.WebsocketTimeoutError:1
msgid "ベースクラス: :class:`qiskit.providers.ibmq.api.exceptions.WebsocketError`"
msgstr ""

#: ../../../../../../../../anaconda3/envs/myQiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/exceptions.py:docstring of qiskit.providers.ibmq.api.exceptions.WebsocketTimeoutError:1
msgid "Timeout during websocket communication."
msgstr ""

